[package]
name = "arcana-timespan"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2018"


[features]
std = []
default = ["std"]

[dependencies]
serde = { version = "1.0", optional = true }
